name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk
          pip install --upgrade pip
          pip install buildozer cython==0.29.37

      - name: Setup Android SDK path
        run: |
          mkdir -p $HOME/android-sdk
          chmod -R 777 $HOME/android-sdk
          echo "ANDROIDSDK=$HOME/android-sdk" >> $GITHUB_ENV

      - name: Build APK
        run: |
          export ANDROIDSDK=$HOME/android-sdk
          export ANDROIDNDK=$HOME/android-ndk
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: CalculatorApp-APK
          path: bin/*.apk
